name: DNABind
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openmm
  - ambertools
  - pdbfixer
  - biopython
  - numpy
  - mdtraj
  - openmmforcefields
  - pip
  - pip:
      # For optional ML potentials (TorchMD-NET), uncomment the next line:
      # - torchmd-net
